name: 部署blog到github pages

on:
  push:
    branches:
      - master
    paths:
      - '_posts/**'
      - '_includes/**'
      - '_layouts/**'
      - '_sass/**'
      - 'tag/**'

jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hasFiles('**/Gemfile') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - uses: helaili/jekyll-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
